"""Added created_at column

Revision ID: 1e6246abe919
Revises: 
Create Date: 2025-02-27 02:42:00.000670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6246abe919'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conversations', 'character',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conversations', 'character',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('conversations', 'created_at')
    # ### end Alembic commands ###
